config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
         sessions: 'users/sessions',
    registrations: 'users/registrations',
      invitations: 'users/invitations',
        passwords: 'users/passwords'
  }
  resources :homes
  root 'homes#index'

  namespace :user do
    resources :users, except: %i[edit update delete] do
      collection do
        get :friend
      end
    end
    resources :follows, only: :index do
      collection do
        put :follow
        put :unfollow
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">CAY</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Friends',friend_user_users_path, class: 'nav-link active', 'aria-current' => 'page' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profile
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
          </ul>
        </li>
      </ul>
      <%= form_for root_path, class: 'd-flex', method: :get do %>
        <%= text_field_tag 'q[email_or_username_cont]', '', class: 'form-control me-2', placeholder: 'Search' %>
        <%= button_tag 'Search', class: 'btn btn-outline-success' %>
      <% end %>
    </div>
  </div>
</nav>