config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
         sessions: 'users/sessions',
    registrations: 'users/registrations',
      invitations: 'users/invitations',
        passwords: 'users/passwords'
  }
  resources :homes
  root 'homes#index'

  namespace :user do
    resources :users, except: %i[edit update delete] do
      collection do
        get :friend
      end
    end
    resources :follows, only: :index do
      collection do
        put :follow
        put :unfollow
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result.without_self(current_user)
  end
end

app/views/homes/index.html.erb
<h3>Username: <%= current_user.username %></h3>
<h4>Followings: <%= current_user.followees.count %></h4>
<h4>Followers: <%= current_user.followers.count %></h4>

<% if params[:q].present? %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">Email</th>
        <th scope="col">Username</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each_with_index do |user, idx| %>
      <tr>
        <th><%= idx + 1 %></th>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td>
          <% if current_user.follow?(user) %>
            <%= button_to 'Unfollow', unfollow_user_follows_path(id: user.id), class: 'btn btn-danger', method: :put %>
          <% else %>
            <%= button_to 'Follow', follow_user_follows_path(id: user.id), class: 'btn btn-primary', method: :put %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>